
include $(PROJROOT)/make/project.make

# directory name of this leaf
#############################
LEAF = smachine

#############################################
# source file list in this directory, fill in
#  CFILES         (*.c)
#  CCFILES        (*.cc)
#  CPPFILES       (*.cpp)
#############################################
CFILES = $(LEAF).c sm_states.c sm_misc.c
CCFILES =
CPPFILES =

include $(MAKEINC)/target.process

include $(LEAF).dpd

