
include $(PROJROOT)/make/project.make

# directory name of this leaf
#############################
LEAF = message

#############################################
# source file list in this directory, fill in
#  CFILES         (*.c)
#  CCFILES        (*.cc)
#  CPPFILES       (*.cpp)
#############################################
CFILES = $(LEAF).c
CCFILES =
CPPFILES =

include $(MAKEINC)/target.library

include $(LEAF).dpd

