
include $(PROJROOT)/make/project.make

# directory name of this leaf
#############################
LEAF = io

#############################################
# source file list in this directory, fill in
#  CFILES         (*.c)
#  CCFILES        (*.cc)
#  CPPFILES       (*.cpp)
#############################################
CFILES = $(LEAF).c io_handlers.c io_simulate.c
CCFILES =
CPPFILES =

include $(MAKEINC)/target.process

include $(LEAF).dpd

