
include $(PROJROOT)/make/project.make
include $(PROJROOT)/make/target.node

# list of sub-directories in this node,
# that recursive make system should descend
###########################################

DIRS = lib proc

